---

- hosts: all
  gather_facts: true
  become: true
 
  tasks:
    #- name: update repository index
    #apt:
    #update_cache: yes
    #when: ansible_distribution in ["Debian", "Ubuntu"]
    # when: ansible_distribution == "Ubuntu"
    #if we have multiple distributions we can use the line below
    #    when: ansible_distribution in ["Debian","Ubuntu"]
      
    #We might also need to specify the distribution and its version
    # when: ansible_distribution == "Ubuntu"and ansible_distribution_version == "8.2"

  - name: install apache2 package, support for php and update repository
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
        #    when: ansible_distribution in ["Debian", "Ubuntu"]
    # when: ansible_distribution == "Ubuntu"
    #    when: ansible_distribution in ["Debian","Ubuntu"]

        #  - name: add php support for apache for Kali_Linux
        #    apt:
        #      name: 
        #        - libapache2-mod-php
        #      state: latest
        #    when: ansible_distribution == "Kali"
    #    when: ansible_distribution == "Ubuntu"
    #    when: ansible_distribution in ["Debian","Ubuntu"]
    #  - name: add php support for Ubuntu
    #    apt:
    # name:
    #   - libapache2-mod-php5
    # state: latest
    #    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"
  #PLAYBOOKS FOR CENTOS

     #- name: update repository index
     #yum:
     #update_cache: yes
     #when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

        #  - name: install apache2 and php package for CentOS
    #    yum:
      #      name: 
        #        - httpd
          #        - php
          #      state: latest
        #      update_cache: yes
        #    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

      #  - name: add php support for apache
      # yum:
      # name: php
      # state: latest
      # when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

