---

- hosts: all
  gather_facts: true
  become: true
 
  tasks:
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]
    # when: ansible_distribution == "Ubuntu"
    #if we have multiple distributions we can use the line below
    #    when: ansible_distribution in ["Debian","Ubuntu"]
      
    #We might also need to specify the distribution and its version
    # when: ansible_distribution == "Ubuntu"and ansible_distribution_version == "8.2"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
    # when: ansible_distribution == "Ubuntu"
    #    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: add php support for apache
    apt:
      name: libapache2-mod-php5
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
    #    when: ansible_distribution == "Ubuntu"
    #    when: ansible_distribution in ["Debian","Ubuntu"]

  #PLAYBOOKS FOR CENTOS
- hosts: CentOS
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

  - name: add php support for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

