---

- hosts: all
  gather_facts: true
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
  
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers_ubuntu
  gather_facts: true
  become: true
  tasks: 

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
     name:
       - apache2
       - libapache2-mod-php5
     state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install apache2 and php package for CentOS
    tags: apache,centos,httpd
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    yum:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Kali)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Kali"

- hosts: file-servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
      #  - name: add php support for apache
      # yum:
      # name: php
      # state: latest
      # when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

